# Site settings
title: VeSinFiltro
email: info@vesinfiltro.com
description: > # this means to ignore newlines until "baseurl:"
  VEsinFiltro es un repositorio de información sobre la censura y filtrado de contenidos en Venezuela. Herramientas para denucniar y evaduar bloqueos y más
tagline: "Infórmate sobre el estado de internet en Venezuela"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vesinfiltro.com" # the base hostname & protocol for your site
twitter_username: vesinfiltro

navigation:
- title: Noticias
  url: /
- title: Reporta
  url: /reporta/
- title: Test
  url: /test/
- title: Evade los bloqueos
  url: /bloqueos/

langs:
- name: Español 
  code: es
  url: /es
- name: Inglés
  code: en
  url: /en

news_categories:
  - name: reporte
    url: /reportes
  - name: alerta
    url: /alerta
  - name: noticia
    url: /noticia

# Build settings
markdown: kramdown

collections:
  bloqueos:
    output: true
  documenta:
    output: true
  noticias:
    output: true


plugins:
- jekyll-redirect-from
- jekyll-paginate


